apiVersion: v1
kind: Namespace
metadata:
  name: skaffold-jib-spring-gradle
---
apiVersion: v1
kind: Service
metadata:
  namespace: skaffold-jib-spring-gradle
  name: web
spec:
  ports:
    - port: 8080
      name: http
  type: LoadBalancer
  selector:
    app: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: skaffold-jib-spring-gradle
  name: web
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: hclcnlabs/skaffold-jib-spring-gradle:0.0.1
          ports:
            - containerPort: 8080
